### ISSUE TITLE
Pause Button Doesn't Actually Pause

### ISSUE THREAD

**Issue by textfiles** [jsmess/jsmess#108]
It turns out that if you press P for pause in a JSMESS emulation, the screen will go darker and nothing will move, but the emulation will continue to run in the background. Pressing P will bring the item "back" but at the point the emulation has gotten to.

**Comment by sehugg** [comment]
Putting this at the beginning of `js_main_loop()` in `src/emu/machine.cpp` did the trick for me:

        if (jsmess_machine->paused()) {
                jsmess_machine->video().frame_update();
                return;
        }

**Comment by DopefishJustin** [comment]
Thanks, committed in https://github.com/mamedev/mame/commit/aba51822ee26ee58e44717c1c22c002588a42085
